//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenstrualCycleReminderDuyVKServiceReference
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MenstrualCycleReminderDuyVK", Namespace = "http://schemas.datacontract.org/2004/07/Gender.SoapApiServices.DuyVK.SoapModels")]
    public partial class MenstrualCycleReminderDuyVK : object
    {

        private int MenstrualCycleReminderDuyVKidField;

        private int ReminderCategoryDuyVKidField;

        private string TitleField;

        private string NoteField;

        private System.DateTime ReminderDateField;

        private System.Nullable<System.DateTime> SentAtField;

        private bool IsSentField;

        private System.Nullable<int> RepeatIntervalField;

        private System.Nullable<double> ImportanceScoreField;

        private System.Nullable<System.DateTime> CreatedAtField;

        private System.Nullable<System.DateTime> UpdatedAtField;

        private MenstrualCycleReminderDuyVKServiceReference.ReminderCategoryDuyVK ReminderCategoryDuyVKField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenstrualCycleReminderDuyVKid
        {
            get
            {
                return this.MenstrualCycleReminderDuyVKidField;
            }
            set
            {
                this.MenstrualCycleReminderDuyVKidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReminderCategoryDuyVKid
        {
            get
            {
                return this.ReminderCategoryDuyVKidField;
            }
            set
            {
                this.ReminderCategoryDuyVKidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public System.DateTime ReminderDate
        {
            get
            {
                return this.ReminderDateField;
            }
            set
            {
                this.ReminderDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public System.Nullable<System.DateTime> SentAt
        {
            get
            {
                return this.SentAtField;
            }
            set
            {
                this.SentAtField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public bool IsSent
        {
            get
            {
                return this.IsSentField;
            }
            set
            {
                this.IsSentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public System.Nullable<int> RepeatInterval
        {
            get
            {
                return this.RepeatIntervalField;
            }
            set
            {
                this.RepeatIntervalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public System.Nullable<double> ImportanceScore
        {
            get
            {
                return this.ImportanceScoreField;
            }
            set
            {
                this.ImportanceScoreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public MenstrualCycleReminderDuyVKServiceReference.ReminderCategoryDuyVK ReminderCategoryDuyVK
        {
            get
            {
                return this.ReminderCategoryDuyVKField;
            }
            set
            {
                this.ReminderCategoryDuyVKField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ReminderCategoryDuyVK", Namespace = "http://schemas.datacontract.org/2004/07/Gender.SoapApiServices.DuyVK.SoapModels")]
    public partial class ReminderCategoryDuyVK : object
    {

        private int ReminderCategoryDuyVKidField;

        private string CodeField;

        private string NameField;

        private string DescriptionField;

        private System.Nullable<bool> IsActiveField;

        private System.Nullable<int> PriorityLevelField;

        private System.Nullable<int> DefaultOffsetField;

        private string ColorCodeField;

        private System.Nullable<System.DateTime> CreatedAtField;

        private System.Nullable<System.DateTime> UpdatedAtField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReminderCategoryDuyVKid
        {
            get
            {
                return this.ReminderCategoryDuyVKidField;
            }
            set
            {
                this.ReminderCategoryDuyVKidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public System.Nullable<int> PriorityLevel
        {
            get
            {
                return this.PriorityLevelField;
            }
            set
            {
                this.PriorityLevelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public System.Nullable<int> DefaultOffset
        {
            get
            {
                return this.DefaultOffsetField;
            }
            set
            {
                this.DefaultOffsetField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public string ColorCode
        {
            get
            {
                return this.ColorCodeField;
            }
            set
            {
                this.ColorCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SearchRequest", Namespace = "http://schemas.datacontract.org/2004/07/Gender.SoapApiServices.DuyVK.SoapModelExt" +
        "ensions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderSearchRequest))]
    public partial class SearchRequest : object
    {

        private System.Nullable<int> CurrentPageField;

        private System.Nullable<int> PageSizeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CurrentPage
        {
            get
            {
                return this.CurrentPageField;
            }
            set
            {
                this.CurrentPageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MenstrualCycleReminderSearchRequest", Namespace = "http://schemas.datacontract.org/2004/07/Gender.SoapApiServices.DuyVK.SoapModelExt" +
        "ensions")]
    public partial class MenstrualCycleReminderSearchRequest : MenstrualCycleReminderDuyVKServiceReference.SearchRequest
    {

        private string TitleField;

        private string ColorCodeField;

        private System.Nullable<double> ImportanceScoreField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string ColorCode
        {
            get
            {
                return this.ColorCodeField;
            }
            set
            {
                this.ColorCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.Nullable<double> ImportanceScore
        {
            get
            {
                return this.ImportanceScoreField;
            }
            set
            {
                this.ImportanceScoreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PaginationResultResponseOfArrayOfMenstrualCycleReminderDuyVK", Namespace = "http://schemas.datacontract.org/2004/07/Gender.SoapApiServices.DuyVK.SoapModelExt" +
        "ensions")]
    public partial class PaginationResultResponseOfArrayOfMenstrualCycleReminderDuyVK : object
    {

        private int CurrentPageField;

        private MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK[] ItemsField;

        private int PageSizeField;

        private int TotalItemsField;

        private int TotalPagesField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage
        {
            get
            {
                return this.CurrentPageField;
            }
            set
            {
                this.CurrentPageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "MenstrualCycleReminderDuyVKServiceReference.IMenstrualCycleReminderDuyVKSoapServi" +
        "ce")]
    public interface IMenstrualCycleReminderDuyVKSoapService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/GetAll", ReplyAction = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/GetAllResponse")]
        System.Threading.Tasks.Task<MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK[]> GetAllAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/GetAllPaged", ReplyAction = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/GetAllPagedResponse")]
        System.Threading.Tasks.Task<MenstrualCycleReminderDuyVKServiceReference.PaginationResultResponseOfArrayOfMenstrualCycleReminderDuyVK> GetAllPagedAsync(MenstrualCycleReminderDuyVKServiceReference.SearchRequest searchRequest);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/GetById", ReplyAction = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/GetByIdResponse")]
        System.Threading.Tasks.Task<MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK> GetByIdAsync(int id);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/Search", ReplyAction = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/SearchResponse")]
        System.Threading.Tasks.Task<MenstrualCycleReminderDuyVKServiceReference.PaginationResultResponseOfArrayOfMenstrualCycleReminderDuyVK> SearchAsync(MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderSearchRequest searchMenstrualCycleReminderRequest);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/Create", ReplyAction = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/Update", ReplyAction = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/Delete", ReplyAction = "http://tempuri.org/IMenstrualCycleReminderDuyVKSoapService/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int id);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IMenstrualCycleReminderDuyVKSoapServiceChannel : MenstrualCycleReminderDuyVKServiceReference.IMenstrualCycleReminderDuyVKSoapService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MenstrualCycleReminderDuyVKSoapServiceClient : System.ServiceModel.ClientBase<MenstrualCycleReminderDuyVKServiceReference.IMenstrualCycleReminderDuyVKSoapService>, MenstrualCycleReminderDuyVKServiceReference.IMenstrualCycleReminderDuyVKSoapService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public MenstrualCycleReminderDuyVKSoapServiceClient() :
                base(MenstrualCycleReminderDuyVKSoapServiceClient.GetDefaultBinding(), MenstrualCycleReminderDuyVKSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMenstrualCycleReminderDuyVKSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MenstrualCycleReminderDuyVKSoapServiceClient(EndpointConfiguration endpointConfiguration) :
                base(MenstrualCycleReminderDuyVKSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), MenstrualCycleReminderDuyVKSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MenstrualCycleReminderDuyVKSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(MenstrualCycleReminderDuyVKSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MenstrualCycleReminderDuyVKSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(MenstrualCycleReminderDuyVKSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MenstrualCycleReminderDuyVKSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }

        public System.Threading.Tasks.Task<MenstrualCycleReminderDuyVKServiceReference.PaginationResultResponseOfArrayOfMenstrualCycleReminderDuyVK> GetAllPagedAsync(MenstrualCycleReminderDuyVKServiceReference.SearchRequest searchRequest)
        {
            return base.Channel.GetAllPagedAsync(searchRequest);
        }

        public System.Threading.Tasks.Task<MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }

        public System.Threading.Tasks.Task<MenstrualCycleReminderDuyVKServiceReference.PaginationResultResponseOfArrayOfMenstrualCycleReminderDuyVK> SearchAsync(MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderSearchRequest searchMenstrualCycleReminderRequest)
        {
            return base.Channel.SearchAsync(searchMenstrualCycleReminderRequest);
        }

        public System.Threading.Tasks.Task<int> CreateAsync(MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK model)
        {
            return base.Channel.CreateAsync(model);
        }

        public System.Threading.Tasks.Task<int> UpdateAsync(MenstrualCycleReminderDuyVKServiceReference.MenstrualCycleReminderDuyVK model)
        {
            return base.Channel.UpdateAsync(model);
        }

        public System.Threading.Tasks.Task<int> DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMenstrualCycleReminderDuyVKSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMenstrualCycleReminderDuyVKSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7227/soap/MenstrualCycleReminderDuyVK.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MenstrualCycleReminderDuyVKSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMenstrualCycleReminderDuyVKSoapService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MenstrualCycleReminderDuyVKSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMenstrualCycleReminderDuyVKSoapService);
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_IMenstrualCycleReminderDuyVKSoapService,
        }
    }
}
