// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gender.Repositories.DuyVK.Models;

public partial class MenstrualCycleReminderDuyVK
{
    public int MenstrualCycleReminderDuyVKid { get; set; }

    public int ReminderCategoryDuyVKid { get; set; }

    public string Title { get; set; }

    public string Note { get; set; }

    public DateTime ReminderDate { get; set; }

    public DateTime? SentAt { get; set; }

    public bool? IsSent { get; set; }

    public int? RepeatInterval { get; set; }

    public double? ImportanceScore { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ReminderCategoryDuyVK ReminderCategoryDuyVK { get; set; }
}