// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Gender.GraphQLClient.BlazorWAS.DuyVK.ModelExtensions;
using System;
using System.Collections.Generic;

namespace Gender.GraphQLClient.BlazorWAS.DuyVK.Models;
public partial class ReminderCategoryDuyVK
{
    public int ReminderCategoryDuyVKid { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public int? PriorityLevel { get; set; }

    public int? DefaultOffset { get; set; }

    public string ColorCode { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<MenstrualCycleReminderDuyVK> MenstrualCycleReminderDuyVKs { get; set; } = new List<MenstrualCycleReminderDuyVK>();
}

// ============================
// === Get, Search
// ============================
public class ReminderCategoryDuyVKListResponse
{
    public PaginationResultResponse<List<ReminderCategoryDuyVK>> reminderCategoryDuyVKList { get; set; }
}

public class ReminderCategoryDuyVKListAllResponse
{
    public List<ReminderCategoryDuyVK> reminderCategoryDuyVKListAll { get; set; }
}

public class ReminderCategoryDuyVKByIdResponse
{
    public ReminderCategoryDuyVK reminderCategoryDuyVKById { get; set; }
}

// ============================
// === Create, Update, Delete
// ============================
public class CreateReminderCategoryDuyVKResponse
{
    public int createReminderCategoryDuyVK { get; set; }
}

public class UpdateReminderCategoryDuyVKResponse
{
    public int updateReminderCategoryDuyVK { get; set; }
}

public class DeleteReminderCategoryDuyVKResponse
{
    public bool deleteReminderCategoryDuyVK { get; set; }
}
