//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReminderCategoryDuyVKServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReminderCategoryDuyVK", Namespace="http://schemas.datacontract.org/2004/07/Gender.SoapApiServices.DuyVK.SoapModels")]
    public partial class ReminderCategoryDuyVK : object
    {
        
        private int ReminderCategoryDuyVKidField;
        
        private string CodeField;
        
        private string NameField;
        
        private string DescriptionField;
        
        private System.Nullable<bool> IsActiveField;
        
        private System.Nullable<int> PriorityLevelField;
        
        private System.Nullable<int> DefaultOffsetField;
        
        private string ColorCodeField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReminderCategoryDuyVKid
        {
            get
            {
                return this.ReminderCategoryDuyVKidField;
            }
            set
            {
                this.ReminderCategoryDuyVKidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> PriorityLevel
        {
            get
            {
                return this.PriorityLevelField;
            }
            set
            {
                this.PriorityLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> DefaultOffset
        {
            get
            {
                return this.DefaultOffsetField;
            }
            set
            {
                this.DefaultOffsetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ColorCode
        {
            get
            {
                return this.ColorCodeField;
            }
            set
            {
                this.ColorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReminderCategoryDuyVKServiceReference.IReminderCategoryDuyVKSoapService")]
    public interface IReminderCategoryDuyVKSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderCategoryDuyVKSoapService/GetAll", ReplyAction="http://tempuri.org/IReminderCategoryDuyVKSoapService/GetAllResponse")]
        System.Threading.Tasks.Task<ReminderCategoryDuyVKServiceReference.ReminderCategoryDuyVK[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IReminderCategoryDuyVKSoapServiceChannel : ReminderCategoryDuyVKServiceReference.IReminderCategoryDuyVKSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ReminderCategoryDuyVKSoapServiceClient : System.ServiceModel.ClientBase<ReminderCategoryDuyVKServiceReference.IReminderCategoryDuyVKSoapService>, ReminderCategoryDuyVKServiceReference.IReminderCategoryDuyVKSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReminderCategoryDuyVKSoapServiceClient() : 
                base(ReminderCategoryDuyVKSoapServiceClient.GetDefaultBinding(), ReminderCategoryDuyVKSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IReminderCategoryDuyVKSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReminderCategoryDuyVKSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ReminderCategoryDuyVKSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), ReminderCategoryDuyVKSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReminderCategoryDuyVKSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReminderCategoryDuyVKSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReminderCategoryDuyVKSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReminderCategoryDuyVKSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReminderCategoryDuyVKSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ReminderCategoryDuyVKServiceReference.ReminderCategoryDuyVK[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReminderCategoryDuyVKSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReminderCategoryDuyVKSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7227/soap/ReminderCategoryDuyVK.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReminderCategoryDuyVKSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IReminderCategoryDuyVKSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReminderCategoryDuyVKSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IReminderCategoryDuyVKSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IReminderCategoryDuyVKSoapService,
        }
    }
}
