// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Gender.Repositories.DuyVK.Models;

public partial class ReminderCategoryDuyVK
{
    [Key]
    public int ReminderCategoryDuyVKid { get; set; }

    [Required]
    public string Code { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public int? PriorityLevel { get; set; }

    public int? DefaultOffset { get; set; }

    [Required]
    public string ColorCode { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<MenstrualCycleReminderDuyVK> MenstrualCycleReminderDuyVKs { get; set; } = new List<MenstrualCycleReminderDuyVK>();
}